apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170572842
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170572842
    app.kubernetes.io/part-of: test-app-170572842
  name: python-basic-170572842
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-170572842
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-170572842
    spec:
      containers:
      - image: quay.io/hacdev/qrearf5a-tenant/test-app-170572842/python-basic-170572842@sha256:b96c04cef1fe66522fe4170206083c6dd392069f0abdf74f14e623613481ebdf
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
