apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170572842
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170572842
    app.kubernetes.io/part-of: test-app-170572842
  name: python-basic-170572842flsw
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-basic-170572842
    weight: null
status: {}
